name: measure

on: [push, pull_request]

jobs:
  measure:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # seed: [0, 100, 200, 300, 400, 500, 600, 700, 800, 900]
        seed: [0]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip3 install -r scripts/requirements.txt

    - name: Prepare tools/
      run: |
        wget -O tools.zip https://img.atcoder.jp/rcl-contest-2021-long/9ee3ca1da522fff7e369dd7f470f1e7a.zip
        unzip -j -d tester tools.zip 'A/tester/*'
        unzip -j -d visualizer tools.zip 'A/visualizer/*'

    - name: Compile the code
      run: |
        g++ -std=c++17 -Wall -O2 -Iac-library -DLOCAL main.cpp

    - name: Measure the score
      run: |
        python3 scripts/measure.py --jobs 2 --count 200 --seed ${{ matrix.seed }}
